package com.example.demo.po;

import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TB_ADMIN_USER
 */
public class AdminUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMIN_USER.id
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   登陆邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMIN_USER.email
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    private String email;

    /**
     * Database Column Remarks:
     *   0为无效，1为有效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMIN_USER.status
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMIN_USER.create_time
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMIN_USER.update_time
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMIN_USER.id
     *
     * @return the value of TB_ADMIN_USER.id
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMIN_USER.id
     *
     * @param id the value for TB_ADMIN_USER.id
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMIN_USER.email
     *
     * @return the value of TB_ADMIN_USER.email
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMIN_USER.email
     *
     * @param email the value for TB_ADMIN_USER.email
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMIN_USER.status
     *
     * @return the value of TB_ADMIN_USER.status
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMIN_USER.status
     *
     * @param status the value for TB_ADMIN_USER.status
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMIN_USER.create_time
     *
     * @return the value of TB_ADMIN_USER.create_time
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMIN_USER.create_time
     *
     * @param createTime the value for TB_ADMIN_USER.create_time
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMIN_USER.update_time
     *
     * @return the value of TB_ADMIN_USER.update_time
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMIN_USER.update_time
     *
     * @param updateTime the value for TB_ADMIN_USER.update_time
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ADMIN_USER
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminUser other = (AdminUser) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ADMIN_USER
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}