package com.example.demo.po;

import java.time.LocalDateTime;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table TB_ADMIN_ROLE
 */
public class AdminRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMIN_ROLE.id
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMIN_ROLE.name
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMIN_ROLE.description
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    private String description;

    /**
     * Database Column Remarks:
     *   0为无效，1为有效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMIN_ROLE.status
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMIN_ROLE.create_time
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TB_ADMIN_ROLE.update_time
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    private LocalDateTime updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMIN_ROLE.id
     *
     * @return the value of TB_ADMIN_ROLE.id
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMIN_ROLE.id
     *
     * @param id the value for TB_ADMIN_ROLE.id
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMIN_ROLE.name
     *
     * @return the value of TB_ADMIN_ROLE.name
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMIN_ROLE.name
     *
     * @param name the value for TB_ADMIN_ROLE.name
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMIN_ROLE.description
     *
     * @return the value of TB_ADMIN_ROLE.description
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMIN_ROLE.description
     *
     * @param description the value for TB_ADMIN_ROLE.description
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMIN_ROLE.status
     *
     * @return the value of TB_ADMIN_ROLE.status
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMIN_ROLE.status
     *
     * @param status the value for TB_ADMIN_ROLE.status
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMIN_ROLE.create_time
     *
     * @return the value of TB_ADMIN_ROLE.create_time
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMIN_ROLE.create_time
     *
     * @param createTime the value for TB_ADMIN_ROLE.create_time
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TB_ADMIN_ROLE.update_time
     *
     * @return the value of TB_ADMIN_ROLE.update_time
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public LocalDateTime getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TB_ADMIN_ROLE.update_time
     *
     * @param updateTime the value for TB_ADMIN_ROLE.update_time
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ADMIN_ROLE
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AdminRole other = (AdminRole) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ADMIN_ROLE
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        return result;
    }
}