spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/test_swagger?allowMultiQueries=true&connectTimeout=60000
    username: root
