package com.example.demo.dao;

import com.example.demo.po.AdminUser;
import com.example.demo.po.AdminUserExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface AdminUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ADMIN_USER
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    long countByExample(AdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ADMIN_USER
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    int deleteByExample(AdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ADMIN_USER
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ADMIN_USER
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    int insert(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ADMIN_USER
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    int insertSelective(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ADMIN_USER
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    List<AdminUser> selectByExample(AdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ADMIN_USER
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    AdminUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ADMIN_USER
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    int updateByExampleSelective(@Param("record") AdminUser record, @Param("example") AdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ADMIN_USER
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    int updateByExample(@Param("record") AdminUser record, @Param("example") AdminUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ADMIN_USER
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    int updateByPrimaryKeySelective(AdminUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TB_ADMIN_USER
     *
     * @mbg.generated Sun Nov 13 13:41:41 CST 2022
     */
    int updateByPrimaryKey(AdminUser record);
}